### ISSUE TITLE
Add an option to return a 406 response

### ISSUE THREAD

**Issue by oscarotero** [middlewares/negotiation#5]
More info: https://evertpot.com/http/406-not-acceptable

**Comment by thepercival** [comment]
Hello,

I noticed that the browser edge does not send an accept-header when doing an OPTIONS-request. Postman or chrome does send the header { 'Accept': '*/*' } by default. 

I use Slim Framework 4 like this:
$app->add((new Middlewares\ContentType(['html', 'json']))->errorResponse());

ContentType::detectFromHeader will not found a corresponding mime-type without the accept header. 


I could add the accept-header before the the ContentType-middleware is called when dealing with a OPTIONS-request, but is this the way to handle this problem?

thanks for your effort!

Coen
